(defpackage :cl-threadpool
  (:use :cl)
  (:export :threadpool-execution-error)
  (:export :threadpool-cancellation-error)
  (:export :make-threadpool)
  (:export :threadpoolp)
  (:export :stop)
  (:export :add-job)
  (:export :run-jobs)
  (:export :queue-size)
  (:export :pool-name)
  (:export :pool-stopped-p)
  (:export :worker-thread-p)
  (:export :job-value)
  (:export :job-done-p)
  (:export :cancel-job)
  (:export :job-cancelled-p)
  (:export :*logger*)
  (:export :*job-error-to-report*))


