(defpackage :cl-threadpool
  (:use :cl)
  (:export :job-execution-error)
  (:export :job-execution-error-pool-name)
  (:export :job-execution-error-thread-id)
  (:export :job-execution-error-message)
  (:export :job-cancellation-error)
  (:export :make-threadpool)
  (:export :threadpoolp)
  (:export :stop)
  (:export :add-job)
  (:export :run-jobs)
  (:export :queue-size)
  (:export :pool-name)
  (:export :pool-stopped-p)
  (:export :worker-thread-p)
  (:export :job-value)
  (:export :job-done-p)
  (:export :cancel-job)
  (:export :job-cancelled-p)
  (:export :*logger*))


